version: '3'

services:
    postgres:
        build: db
        environment:
            POSTGRES_MULTIPLE_DATABASES: ordering,shipping
            POSTGRES_PASSWORD: dev
            POSTGRES_USER: dev
    ordering-service:
        build: ordering
        links:
            - postgres
        ports:
        -   80:8080
    shipping-service:
        build: shipping
        links:
            - postgres
        ports:
            -   81:8080

