version: '3'
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
    kafka:
        image: wurstmeister/kafka:2.12-2.5.0
        links:
        - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "order:5:1"
    ordering:
        build: ordering
        #image: mohzaar/ms-kafka-order:latest
        links:
            - kafka
        ports:
        - 81:8080
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    shipping:
        build: shipping
        #image: mohzaar/ms-kafka-shipping:latest
        links:
            - kafka
        ports:
            - 82:8080
        environment:
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
