apiVersion: apps/v1 
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: ordering-service
  name: ordering-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ordering-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ordering-service
    spec:
      containers:
      - image: mohzaar/ms-kafka-order:latest
        name: ordering-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
